name: storage_manager_flutter_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  permission_handler_platform_interface: ^3.7.0
  process_run: ^0.12.3+2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
